name: Standard ROS Build Checker

on:
    push:
    pull_request:

jobs:
  ros-build-jazzy:
    uses: qualcomm-qrb-ros/qrb_ros_gh_actions/.github/workflows/ubuntu-build.yml@test/lyrical-ci-preview
    secrets: inherit
    # ros-distro defaults to jazzy, no explicit with needed

  ros-build-lyrical:
    uses: qualcomm-qrb-ros/qrb_ros_gh_actions/.github/workflows/ubuntu-build.yml@test/lyrical-ci-preview
    secrets: inherit
    with:
      ros-distro: lyrical
